name: StarryTown
version: '${project.version}'
main: com.mcstarrysky.starrytown.StarryTown
api-version: 1.19
authors: [ Mical ]
folia-supported: true
commands:
  starrytown:
    usage: "/starrytown help"
    aliases:
      - town
